### ISSUE TITLE
Belgium

### ISSUE THREAD

**Issue by CMiles1979** [Hurqalia/weather_map#1]
Hello can you add Belgium?

**Comment by Hurqalia** [comment]
Yes no problem. I tell you when it's ok

**Comment by Hurqalia** [comment]
it's done, you can load your country from "Weather Map Config" menu. Tell me if you want more cells.

**Comment by CMiles1979** [comment]
Hello ... thank you and I like your other scripts too :)

2016-08-10 21:52 GMT+02:00 Hurqalia notifications@github.com:

> Yes no problem. I tell you when it's ok
>
