### ISSUE TITLE
Please include Brazil Cells

### ISSUE THREAD

**Issue by itaymbere** [Hurqalia/weather_map#2]
We are traking Brazil Cells, could you please include them all?
Above all brazil cell list comma separated
AF01-CHARLIE-11, AF01-CHARLIE-12, AF01-CHARLIE-13, AF01-CHARLIE-14, AF01-CHARLIE-15, AF01-DELTA-00, AF01-DELTA-01, AF01-DELTA-02, AF01-DELTA-03, AF01-DELTA-04, AF01-DELTA-05, AF01-DELTA-06, AF01-DELTA-07, AF01-DELTA-08, AF01-DELTA-09, AF01-DELTA-10, AF01-DELTA-11, AF01-DELTA-12, AF01-DELTA-13, AF01-DELTA-14, AF01-DELTA-15, AF01-ECHO-00, AF01-ECHO-01, AF01-ECHO-02, AF01-ECHO-03, AF01-ECHO-04, AF01-ECHO-05, AF01-ECHO-06, AF01-ECHO-07, AF01-ECHO-08, AF01-ECHO-09, AF01-ECHO-10, AF01-ECHO-11, AF01-ECHO-12, AF01-ECHO-13, AF01-ECHO-14, AF01-ECHO-15, AF01-FOXTROT-00, AF01-FOXTROT-01, AF01-FOXTROT-02, AF01-FOXTROT-03, AF01-FOXTROT-04, AF01-FOXTROT-05, AF01-FOXTROT-06, AF01-FOXTROT-07, AF01-FOXTROT-08, AF01-FOXTROT-09, AF01-FOXTROT-10, AF01-FOXTROT-11, AF01-FOXTROT-12, AF01-FOXTROT-13, AF01-FOXTROT-14, AF01-FOXTROT-15, AF01-GOLF-00, AF01-GOLF-01, AF01-GOLF-02, AF01-GOLF-03, AF01-GOLF-04, AF01-GOLF-05, AF01-GOLF-06, AF01-GOLF-07, AF01-GOLF-08, AF01-GOLF-09, AF01-GOLF-10, AF01-GOLF-11, AF01-GOLF-12, AF01-GOLF-13, AF01-GOLF-14, AF01-GOLF-15, AF01-HOTEL-04, AF01-HOTEL-05, AF01-HOTEL-06, AF01-HOTEL-07, AF01-HOTEL-08, AF01-HOTEL-09, AF01-HOTEL-10, AF01-HOTEL-11, AF01-HOTEL-12, AF02-DELTA-04, AF02-DELTA-05, AF02-ECHO-10, AF02-ECHO-11, AF02-ECHO-12, AF02-ECHO-15, AF02-FOXTROT-00, AF02-FOXTROT-01, AF02-FOXTROT-02, AF02-FOXTROT-03, AF02-FOXTROT-04, AF02-FOXTROT-05, AF02-FOXTROT-06, AF02-FOXTROT-07, AF02-FOXTROT-08, AF02-FOXTROT-09, AF02-FOXTROT-10, AF02-FOXTROT-11, AF02-FOXTROT-13, AF02-GOLF-00, AF02-GOLF-01, AF02-GOLF-02, AF02-GOLF-03, AF02-GOLF-04, AF02-GOLF-05, AF02-GOLF-06, AF02-GOLF-07, AF02-GOLF-08, AF02-GOLF-09, AF02-GOLF-10, AF02-GOLF-11, AF02-GOLF-12, AF02-GOLF-13, AF02-GOLF-14, AF02-GOLF-15, AF02-HOTEL-00, AF02-HOTEL-01, AF02-HOTEL-03, AM07-PAPA-14, AM07-PAPA-15, AM08-MIKE-00, AM08-MIKE-01, AM08-MIKE-02, AM08-MIKE-03, AM08-NOVEMBER-03, AM08-NOVEMBER-04, AM08-NOVEMBER-05, AM08-NOVEMBER-06, AM08-NOVEMBER-07, AM08-NOVEMBER-08, AM08-NOVEMBER-09, AM08-NOVEMBER-10, AM08-NOVEMBER-11, AM08-NOVEMBER-12, AM08-NOVEMBER-13, AM08-NOVEMBER-14, AM08-NOVEMBER-15, AM08-PAPA-00, AM08-PAPA-01, AM08-PAPA-02, AM08-PAPA-03, AM08-PAPA-04, AM08-PAPA-05, AM08-PAPA-06, AM08-PAPA-07, AM08-PAPA-08, AM08-PAPA-09, AM08-PAPA-10, AM08-PAPA-11, AM08-PAPA-14, AM08-SIERRA-14, AM08-SIERRA-15, AM09-MIKE-05, AM09-MIKE-06, AM09-MIKE-08, AM09-MIKE-09, AM09-MIKE-10, AM09-MIKE-11, AM09-MIKE-12, AM09-MIKE-13, AM09-MIKE-14, AM09-MIKE-15, AM09-NOVEMBER-00, AM09-NOVEMBER-01, AM09-NOVEMBER-02, AM09-NOVEMBER-03, AM09-NOVEMBER-04, AM09-NOVEMBER-05, AM09-NOVEMBER-06, AM09-NOVEMBER-07, AM09-NOVEMBER-08, AM09-NOVEMBER-09, AM09-NOVEMBER-10, AM09-NOVEMBER-11, AM09-NOVEMBER-12, AM09-NOVEMBER-13, AM09-NOVEMBER-14, AM09-NOVEMBER-15, AM09-PAPA-00, AM09-PAPA-01, AM09-PAPA-02, AM09-PAPA-03, AM09-PAPA-04, AM09-PAPA-05, AM09-PAPA-06, AM09-PAPA-07, AM09-PAPA-08, AM09-PAPA-09, AM09-PAPA-10, AM09-PAPA-11, AM09-PAPA-12, AM09-PAPA-13, AM09-PAPA-14, AM09-PAPA-15, AM09-ROMEO-00, AM09-ROMEO-01, AM09-ROMEO-02, AM09-ROMEO-03, AM09-ROMEO-04, AM09-ROMEO-05, AM09-ROMEO-06, AM09-ROMEO-07, AM09-ROMEO-08, AM09-ROMEO-09, AM09-ROMEO-10, AM09-ROMEO-11, AM09-ROMEO-12, AM09-ROMEO-13, AM09-ROMEO-14, AM09-ROMEO-15, AM09-SIERRA-00, AM09-SIERRA-01, AM09-SIERRA-02, AM09-SIERRA-03, AM09-SIERRA-04, AM09-SIERRA-06, AM09-SIERRA-07, AM09-SIERRA-08, AM09-SIERRA-09, AM09-SIERRA-10, AM09-SIERRA-11, AM09-SIERRA-12, AM09-SIERRA-13, AM09-SIERRA-14, AM09-SIERRA-15, AM10-LIMA-01, AM10-LIMA-14, AM10-MIKE-00, AM10-MIKE-01, AM10-MIKE-02, AM10-MIKE-03, AM10-MIKE-04, AM10-MIKE-05, AM10-MIKE-06, AM10-MIKE-07, AM10-MIKE-08, AM10-MIKE-09, AM10-MIKE-10, AM10-MIKE-11, AM10-MIKE-12, AM10-MIKE-13, AM10-MIKE-14, AM10-MIKE-15, AM10-NOVEMBER-00, AM10-NOVEMBER-01, AM10-NOVEMBER-02, AM10-NOVEMBER-03, AM10-NOVEMBER-04, AM10-NOVEMBER-05, AM10-NOVEMBER-06, AM10-NOVEMBER-07, AM10-NOVEMBER-08, AM10-NOVEMBER-09, AM10-NOVEMBER-10, AM10-NOVEMBER-11, AM10-NOVEMBER-12, AM10-NOVEMBER-13, AM10-NOVEMBER-14, AM10-NOVEMBER-15, AM10-PAPA-00, AM10-PAPA-01, AM10-PAPA-02, AM10-PAPA-03, AM10-PAPA-04, AM10-PAPA-05, AM10-PAPA-06, AM10-PAPA-07, AM10-PAPA-08, AM10-PAPA-09, AM10-PAPA-10, AM10-PAPA-11, AM10-PAPA-12, AM10-PAPA-13, AM10-PAPA-14, AM10-PAPA-15, AM10-ROMEO-00, AM10-ROMEO-01, AM10-ROMEO-02, AM10-ROMEO-03, AM10-ROMEO-04, AM10-ROMEO-05, AM10-ROMEO-06, AM10-ROMEO-07, AM10-ROMEO-08, AM10-ROMEO-09, AM10-ROMEO-10, AM10-ROMEO-11, AM10-ROMEO-12, AM10-ROMEO-13, AM10-ROMEO-14, AM10-ROMEO-15, AM10-SIERRA-00, AM10-SIERRA-01, AM10-SIERRA-02, AM10-SIERRA-03, AM10-SIERRA-04, AM10-SIERRA-05, AM10-SIERRA-06, AM10-SIERRA-07, AM10-SIERRA-08, AM10-SIERRA-09, AM10-SIERRA-10, AM10-SIERRA-11, AM10-SIERRA-12, AM10-SIERRA-13, AM10-SIERRA-14, AM10-SIERRA-15, AM11-MIKE-11, AM11-MIKE-12, AM11-MIKE-15, AM11-NOVEMBER-00, AM11-NOVEMBER-02, AM11-NOVEMBER-03, AM11-NOVEMBER-04, AM11-NOVEMBER-05, AM11-NOVEMBER-06, AM11-NOVEMBER-07, AM11-NOVEMBER-08, AM11-NOVEMBER-09, AM11-NOVEMBER-10, AM11-NOVEMBER-13, AM11-PAPA-00, AM11-PAPA-01, AM11-PAPA-02, AM11-PAPA-03, AM11-PAPA-04, AM11-PAPA-05, AM11-PAPA-06, AM11-PAPA-07, AM11-PAPA-08, AM11-PAPA-09, AM11-PAPA-10, AM11-PAPA-11, AM11-PAPA-12, AM11-PAPA-13, AM11-PAPA-14, AM11-PAPA-15, AM11-ROMEO-00, AM11-ROMEO-01, AM11-ROMEO-02, AM11-ROMEO-03, AM11-ROMEO-04, AM11-ROMEO-05, AM11-ROMEO-06, AM11-ROMEO-07, AM11-ROMEO-08, AM11-ROMEO-09, AM11-ROMEO-10, AM11-ROMEO-11, AM11-ROMEO-12, AM11-ROMEO-13, AM11-ROMEO-14, AM11-ROMEO-15, AM11-SIERRA-00, AM11-SIERRA-01, AM11-SIERRA-02, AM11-SIERRA-03, AM11-SIERRA-04, AM11-SIERRA-05, AM11-SIERRA-06, AM11-SIERRA-07, AM11-SIERRA-08, AM11-SIERRA-09, AM11-SIERRA-10, AM11-SIERRA-11, AM11-SIERRA-12, AM11-SIERRA-13, AM11-SIERRA-14, AM11-SIERRA-15, AM12-PAPA-00, AM12-PAPA-01, AM12-PAPA-02, AM12-PAPA-03, AM12-PAPA-07, AM12-PAPA-08, AM12-PAPA-09, AM12-PAPA-10, AM12-PAPA-11, AM12-PAPA-12, AM12-PAPA-13, AM12-PAPA-14, AM12-PAPA-15, AM12-ROMEO-00, AM12-ROMEO-01, AM12-ROMEO-02, AM12-ROMEO-03, AM12-ROMEO-04, AM12-ROMEO-05, AM12-ROMEO-06, AM12-ROMEO-07, AM12-ROMEO-08, AM12-ROMEO-09, AM12-ROMEO-10, AM12-ROMEO-11, AM12-ROMEO-12, AM12-ROMEO-13, AM12-ROMEO-14, AM12-ROMEO-15, AM12-SIERRA-00, AM12-SIERRA-01, AM12-SIERRA-02, AM12-SIERRA-03, AM12-SIERRA-04, AM12-SIERRA-05, AM12-SIERRA-06, AM12-SIERRA-07, AM12-SIERRA-08, AM12-SIERRA-09, AM12-SIERRA-10, AM12-SIERRA-11, AM12-SIERRA-12, AM12-SIERRA-13, AM12-SIERRA-14, AM12-SIERRA-15, AM13-PAPA-00, AM13-PAPA-01, AM13-PAPA-02, AM13-PAPA-12, AM13-PAPA-13, AM13-PAPA-14, AM13-PAPA-15, AM13-ROMEO-00, AM13-ROMEO-01, AM13-ROMEO-02, AM13-ROMEO-03, AM13-ROMEO-04, AM13-ROMEO-05, AM13-ROMEO-06, AM13-ROMEO-07, AM13-ROMEO-08, AM13-ROMEO-09, AM13-ROMEO-10, AM13-ROMEO-11, AM13-ROMEO-12, AM13-ROMEO-13, AM13-ROMEO-14, AM13-ROMEO-15, AM13-SIERRA-00, AM13-SIERRA-01, AM13-SIERRA-02, AM13-SIERRA-03, AM13-SIERRA-04, AM13-SIERRA-05, AM13-SIERRA-06, AM13-SIERRA-07, AM13-SIERRA-08, AM13-SIERRA-09, AM13-SIERRA-10, AM13-SIERRA-11, AM13-SIERRA-12, AM13-SIERRA-13, AM13-SIERRA-14, AM13-SIERRA-15, AM14-PAPA-09, AM14-PAPA-10, AM14-ROMEO-00, AM14-ROMEO-01, AM14-ROMEO-02, AM14-ROMEO-03, AM14-ROMEO-04, AM14-ROMEO-05, AM14-ROMEO-06, AM14-ROMEO-07, AM14-ROMEO-08, AM14-ROMEO-09, AM14-ROMEO-10, AM14-ROMEO-11, AM14-ROMEO-12, AM14-ROMEO-13, AM14-ROMEO-14, AM14-ROMEO-15, AM14-SIERRA-00, AM14-SIERRA-01, AM14-SIERRA-02, AM14-SIERRA-03, AM14-SIERRA-04, AM14-SIERRA-05, AM14-SIERRA-06, AM14-SIERRA-07, AM14-SIERRA-08, AM14-SIERRA-09, AM14-SIERRA-12, AM14-SIERRA-13, AM14-SIERRA-14, AM14-SIERRA-15, AM15-PAPA-05, AM15-PAPA-06, AM15-ROMEO-00, AM15-ROMEO-01, AM15-ROMEO-02, AM15-ROMEO-03, AM15-ROMEO-06, AM15-ROMEO-07, AM15-ROMEO-08, AM15-ROMEO-09, AM15-ROMEO-10, AM15-ROMEO-11, AM15-ROMEO-12, AM15-ROMEO-13, AM15-ROMEO-14, AM15-ROMEO-15, AM15-SIERRA-00, AM15-SIERRA-01, AM15-SIERRA-03

**Comment by Hurqalia** [comment]
it's ok. Just open or reload your map, open "Weather Map Config" and choose Brazil from the menu.

**Comment by itaymbere** [comment]
Many many thanks good friend.
I'm also a developer, in case you need some help feel free to contact me!

**Comment by Hurqalia** [comment]
you're welcome, have fun ;)
